# This file stores configurations for your Shopify app.

name = "nested-tabs-app"
client_id = "REPLACE_WITH_YOUR_CLIENT_ID"
application_url = "REPLACE_WITH_YOUR_TUNNEL_URL"
embedded = true

[access_scopes]
# Read more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "REPLACE_WITH_YOUR_TUNNEL_URL/auth/callback" ]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
