name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.19.1]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
      
    - name: Type check
      run: |
        echo "Running type check..."
        npx tsc --noEmit --pretty
      
    - name: Build
      run: |
        echo "Running build..."
        npm run build --if-present
      env:
        CI: false # This prevents treating warnings as errors 